---
# tasks file for docker_server

- name: Install kernel extras for AUFS support
  apt: name="{{ item }}" update_cache=yes
  with_items:
    - linux-image-extra-{{ ansible_kernel }}
    - linux-image-extra-virtual
  notify:
    - restart docker

- name: Add docker apt key.
  apt_key: keyserver=keyserver.ubuntu.com id=36A1D7869245C8950F966E92D8576A8BA88D21E9

- name: Add Docker repository.
  apt_repository: repo='deb https://get.docker.io/ubuntu docker main' state=present

- name: Install support packages
  apt: name="{{ item }}"
  with_items:
    - wget

- name: Install docker package
  apt: name="{{ item }}"
  with_items:
    - "{% if docker_version is defined %}lxc-docker-{{ docker_version }}{% else %}lxc-docker{% endif %}"

- name: Allow external access
  template: src=etc_default_docker dest=/etc/default/docker
  notify:
    - restart docker

- name: Start docker
  service: name=docker state=started
