---
# tasks file for tsuru_api

- name: Add tsuru repositories.
  apt_repository: repo='ppa:tsuru/ppa' update_cache=yes

- name: Install packages.
  apt: update_cache=true name="{{ item }}"
  with_items: packages

- name: Copy configuration file.
  template: src=tsuru.conf.j2 dest=/etc/tsuru/tsuru.conf
  notify:
    - restart tsuru_api

- name: Copy tsuru-server file.
  template: src=tsuru-server.j2 dest=/etc/default/tsuru-server
  notify:
    - restart tsuru_api

