language: python
python: '2.7'
env:
- ANSIBLE_VERSION=1.7
- ANSIBLE_VERSION=1.8
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y curl
install:
- pip install ansible==$ANSIBLE_VERSION
- '{ echo ''[defaults]''; echo ''roles_path = ../''; } >> ansible.cfg'
script:
- ansible-playbook -i tests/hosts tests/test.yml --syntax-check
- ansible-playbook -i tests/hosts tests/test.yml --connection=local --sudo
- |
  ansible-playbook -i tests/hosts tests/test.yml --connection=local --sudo | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
- curl http://localhost:5000
notifications:
  slack:
    secure: FCNkjKkd2oesFcIsvFekb7GtWVniyT8a9fH1mvp9LOg3AJ1ZpDoOnuvuOXJTrNM8rmuqo+GAu9GzB1yCTmbjBlhyVAoeiV1N5qRctN4NbA5FohDRbKAY2Bgp4Q1nFRlGmjbdx45AZAzQNMD3Ni5Hfqiwf0voNS/qS8zYXtAG8rc=
