---

- name: mongodb reload
  service: name={{ mongodb_daemon_name }} state=reloaded

- name: mongodb restart
  service: name={{ mongodb_daemon_name }} state=restarted

- name: mongodb-mms-automation-agent restart
  service: name=mongodb-mms-automation-agent state=restarted

- name: reload systemd
  shell: systemctl daemon-reload
  when: systemd.stat.exists == true
